In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas
import statsmodels.api as sm

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
df = pandas.read_csv("/content/drive/MyDrive/food /book 1.csv")

In [ ]:
df

petrol  vegetables  food
0      90          50    20
1      91          55    21
2      95          60    22
3      97          62    24
4      99          65    28
5     100          75    30
6     105          80    35
7     110          85    40

In [ ]:
x=df.drop(['food'],axis=1)
y=df['food']

In [ ]:
x

petrol  vegetables
0      90          50
1      91          55
2      95          60
3      97          62
4      99          65
5     100          75
6     105          80
7     110          85

In [ ]:
y

0    20
1    21
2    22
3    24
4    28
5    30
6    35
7    40
Name: food, dtype: int64

In [ ]:
type(x)

pandas.core.frame.DataFrame

In [ ]:
type(y)

pandas.core.series.Series

In [ ]:
x=x.values
y=y.values

In [ ]:
type(x)

numpy.ndarray

In [ ]:
type(y)

numpy.ndarray

In [ ]:
#splittingthe dataset into the traning set and test set
from sklearn.model_selection import train_test_split
x_training_set,x_testing_set,y_training_set,y_testing_set=train_test_split(x,y,test_size=0.2,random_state=0)


In [ ]:
x_testing_set

array([[105,  80],
       [ 95,  60]])

In [ ]:
x_training_set

array([[ 91,  55],
       [110,  85],
       [ 97,  62],
       [ 90,  50],
       [100,  75],
       [ 99,  65]])

In [ ]:
y_training_set

array([21, 40, 24, 20, 30, 28])

In [ ]:
y_testing_set

array([35, 22])

In [ ]:
#Fitting multiple linear regression to the traning set
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_training_set,y_training_set)

LinearRegression()

In [ ]:
regressor

LinearRegression()

In [ ]:
#the coefficient
print('cofficients: \n',regressor.coef_)

cofficients: 
 [0.73563502 0.15621455]


In [ ]:
regressor.intercept_

-55.008976572133164

In [ ]:
#prediciting the test set results
y_pred=regressor.predict(x_testing_set)
y_pred

array([34.72986436, 24.24922318])

In [ ]:
from sklearn.metrics import mean_squared_error
#the mean squared error


print("Mean squared error:",mean_squared_error(y_testing_set,y_pred))

Mean squared error: 2.565989090206968


In [ ]:
#explained variance score: 1 is perfect predicition 
from sklearn.metrics import r2_score
print("varance score:",r2_score(y_testing_set,y_pred))

varance score: 0.9392665304093025


In [ ]:
#compare actual data with predicted data
import pandas as pd
y_test=pd.DataFrame(y_testing_set)
y_prediction =pd.DataFrame(y_pred)
comparison =pd.concat([y_test,y_prediction],axis=1)

In [ ]:
comparison.to_csv('regression comparison.csv')

In [ ]:
comparison

0          0
0  35  34.729864
1  22  24.249223

In [ ]:
df

petrol  vegetables  food
0      90          50    20
1      91          55    21
2      95          60    22
3      97          62    24
4      99          65    28
5     100          75    30
6     105          80    35
7     110          85    40

In [ ]:
df.columns

Index(['petrol', 'vegetables', 'food'], dtype='object')

In [ ]:
x=df.drop(['food'],axis=1)
y=df['food']

In [ ]:
x=sm.add_constant(x)
model=sm.OLS(y,x).fit()

/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/tsatools.py:117: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


In [ ]:
summary = model.summary()
print(summary)

                            OLS Regression Results                            
Dep. Variable:                   food   R-squared:                       0.971
Model:                            OLS   Adj. R-squared:                  0.960
Method:                 Least Squares   F-statistic:                     84.10
Date:                Fri, 06 May 2022   Prob (F-statistic):           0.000142
Time:                        05:01:46   Log-Likelihood:                -12.398
No. Observations:                   8   AIC:                             30.80
Df Residuals:                       5   BIC:                             31.03
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        -55.0356     22.399     -2.457      0.0

/usr/local/lib/python3.7/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  "anyway, n=%i" % int(n))


In [ ]:
#calculation of VIF
from statsmodels.stats.outliers_influence import variance_inflation_factor 

#calculating VIF for each feature
#calculate VIF for each explanatory variable 

vif = pd.DataFrame()

vif['VIF']=[variance_inflation_factor(x.values,i)for i in range(x.shape[1])]

vif['variable']=x.columns

print(vif)

           VIF    variable
0  1930.921802       const
1    19.162480      petrol
2    19.162480  vegetables


In [ ]:
#linear regression using gradient decent method
import numpy as np
import matplotlib.pyplot as plt 


x = 2* np.random.rand(100,1)
y=4 + 3*x+np.random.rand(100,1)

In [ ]:
#linear regression using OLS

from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression()
lin_reg.fit(x,y)
lin_reg.intercept_,lin_reg.coef_




(array([4.4582486]), array([[3.05551035]]))

In [ ]:
from sklearn.linear_model import SGDRegressor
sgd_reg=SGDRegressor(n_iter=50,penalty=None,eta=0.1)
sgd_reg.fit(x,y.ravel())
sgd_reg.intercept_, sgd_reg.coef_


TypeError: ignored